[package]
name = "argon2"
version = "0.1.0"
authors = ["ExPixel <adolphc@outlook.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
bitflags = "1.1"
[build-dependencies]
cc = "1.0.37"
bindgen = "0.49"
